config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :articles
    get :setup, to: "setup#edit"
    post :setup, to: "setup#update"

    root to: 'articles#index'
  end

  get ":slug", to: "home#index"

  root to: 'home#index'
  resources :bloggers, path: "" do
    resources :articles, path: "" do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable

  belongs_to :user
  has_many :comments

  mount_uploader :cover, CoverUploader

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  belongs_to :user
  has_many :articles, through: :user

  DEFAULT_TITLE = "Blog"
  DEFAULT_SLUG = "blog-"

  def self.random_slug
    DEFAULT_SLUG + [*('a'..'z'),*('0'..'9')].shuffle[0,8].join
  end

  def owner? current_user
    user == current_user
  end

  def to_param
    self.slug
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_one :blogger, dependent: :destroy
  after_create :setup_blog

private

  def setup_blog
    self.create_blogger(title: Blogger::DEFAULT_TITLE, slug: Blogger.random_slug)
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    layout 'admin'
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::ApplicationController
    def index
      @blog = current_user.blogger
      @articles = @blog.articles
    end

    def new
      @blog = current_user.blogger
      @article = @blog.articles.new
    end

    def create
      @article = current_user.articles.new(article_param)

      if @article.save
        flash[:success] = "Artigo criado!"
        redirect_to admin_articles_path
      else
        flash.now[:alert] = "Preencha os campos corretamente"
        render :new
      end
    end

    def edit
      @blog = current_user.blogger
      @article = current_user.articles.find(params[:id])
    end

    def update
      @article = current_user.articles.find(params[:id])

      if @article.update(article_param)
        flash[:success] = "Artigo editado!"
        redirect_to admin_articles_path
      else
        flash.now[:alert] = "Preencha os campos corretamente"
        render :new
      end
    end

    private

    def article_param
      params.require(:article).permit(:name, :description, :content, :cover, :tag_list)
    end
  end
end

app/controllers/admin/setup_controller.rb
module Admin
  class SetupController < Admin::ApplicationController
    def edit
      @blog = current_user.blogger
    end

    def update
      @blog = current_user.blogger
      @blog.update(blogger_params)

      redirect_to admin_setup_path
    end

    private

    def blogger_params
      params.require(:blogger).permit(:title, :slug, :description)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @blog =  Blogger.find_by_slug(params[:blogger_id])
    @articles = @blog.articles
  end

  def show
    @blog =  Blogger.find_by_slug(params[:blogger_id])
    @article = @blog.articles.find(params[:id])
    @comment = @article.comments.build
  end
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog =  Blogger.find_by_slug(params[:blogger_id])
    @article = @blog.articles.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to blogger_article_path(@blog, @article)
  end

  def destroy
    @blog =  Blogger.find_by_slug(params[:blogger_id])
    if @blog.owner?(current_user)
      @article = @blog.articles.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.delete
      redirect_to blogger_article_path(@blog, @article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:slug].present?
      @blog =  Blogger.find_by_slug(params[:slug])
      @articles = @blog.articles

      render 'articles/index'
    else
      redirect_to admin_setup_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.erb
<%= tinymce_assets %>
<%= form_for [:admin, @article], html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col s12 input-field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 input-field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 input-field">
      <%= f.label :tag_list %>
      <%= f.text_field :tag_list, value: @article.tag_list.to_s %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 input-field">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "tinymce" %>
      <%= tinymce %>
    </div>
  </div>
  <div class="row">
    <div class="col s12 file-field input-field">
      <div class="btn">
        <span>Capa</span>
        <%= f.file_field :cover %>
        <%= f.hidden_field :cover_cache %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <button class="btn waves-effect waves-light" type="submit" name="action">Salvar
        <i class="material-icons right">send</i>
      </button>
    </div>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<nav role="navigation" class="title-wrapper">
  <div class="nav-wrapper">
    <span class="title"><i class="arrow"></i> Artigos <i class="arrow"></i> Editar</span>
  </div>
</nav>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/articles/index.html.erb
<nav role="navigation" class="title-wrapper">
  <div class="nav-wrapper">
    <span class="title"><i class="arrow"></i> Artigos</span>
    <ul class="right">
      <li><%= link_to "Novo artigo", [:new, :admin, :article] %></li>
    </ul>
  </div>
</nav>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <table class="highlight bordered">
        <thead>
          <tr>
            <th data-field="id"></th>
            <th data-field="name">Artigos</th>
            <th data-field="actions"></th>
          </tr>
        </thead>

        <tbody>

          <% @articles.each do |article| %>
            <tr>
              <td>#<%= article.id %></td>
              <td><%= article.name %></td>
              <td class="center">
                <%= link_to "editar", [:edit, :admin, article] %><br />
                <%= link_to "visualizar", blogger_article_path(@blog.slug, article) %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
<nav role="navigation" class="title-wrapper">
  <div class="nav-wrapper">
    <span class="title"><i class="arrow"></i> Artigos <i class="arrow"></i> Novo</span>
  </div>
</nav>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/setup/edit.html.erb
<nav role="navigation" class="title-wrapper">
  <div class="nav-wrapper">
    <span class="title"><i class="arrow"></i> Configurações</span>
  </div>
</nav>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <%= form_for @blog, url: admin_setup_path, method: :post do |f| %>
        <div class="row">
          <div class="col s12 input-field">
            <%= f.label :title %>
            <%= f.text_field :title %>
          </div>
        </div>
        <div class="row">
          <div class="col s12 input-field">
            <%= f.label :slug %>
            <%= f.text_field :slug %>
          </div>
        </div>
        <div class="row">
          <div class="col s12 input-field">
            <%= f.label :description %>
            <%= f.text_field :description %>
          </div>
        </div>

        <div class="row">
          <div class="col s12">
            <button class="btn waves-effect waves-light" type="submit" name="action">Salvar
              <i class="material-icons right">send</i>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row articles">
  <div class="col s12 l8" style="min-height: 400px;">

    <% @articles.each do |article| %>

    <div class="article card">
      <% if article.cover? %>
        <div clas="card-image">
          <%= image_tag article.cover_url, alt: "Article pic" %>
        </div>
      <% end %>
      <div class="card-title"><%= link_to article.name, blogger_article_path(@blog, article) %></div>
      <em class="card-description grey-text text-darken-2">Postado em <%= article.created_at.to_date %></em>
      <div class="card-content">
        <p><%= article.description %></p>

        <div class="divider"></div>
        <%= link_to "Ler mais", blogger_article_path(@blog.slug, article), class: "btn-flat btn-large" %>
      </div>
    </div>

    <% end %>
  </div>

  <%= render "layouts/most_viewed" %>

  <%= render "layouts/tags", tags: ActsAsTaggableOn::Tag.most_used(10) %>
</div>

app/views/articles/show.html.erb
<div class="row articles">
  <div class="col s12 l8">

    <div class="article card">
      <% if @article.cover? %>
        <div clas="card-image">
          <%= image_tag @article.cover_url, alt: "Article pic" %>
        </div>
      <% end %>
      <div class="card-title"><%= link_to @article.name, blogger_article_path(@blog, @article) %></div>
      <em class="card-description grey-text text-darken-2">Postado em <%= Date.today %></em>
      <div class="card-content">
        <p><%= @article.description %></p>
      </div>
      <div class="card-content">
        <p style="text-align: justify;"><%= raw @article.content %></p>
      </div>
    </div>

    <%= render "comments/comments" %> 
  </div>



  <%= render "layouts/most_viewed" %>

  <%= render "layouts/tags", tags: @article.tags %>
</div>

app/views/comments/_comments.html.erb
<%= render "comments/form" %>
<div class="comments card">
  <div class="card-title"><h5>Comentários (<%= @article.comments.count %>)</h5></div>

  <% if @article.comments.count > 0 %>
    <% @article.comments.where.not(id: nil).each do |comment| %>
      <div class="card-content">
        <%= image_tag "/images/avatar.png", class: "avatar" %>
        <p>
          <strong>Nome:</strong>
          <%= comment.commenter %>
        </p>
        <p>
          <strong>Comentário:</strong><br>
          <%= comment.body %>
        </p>
        <% if @blog.owner?(current_user) %>
          <br>
          <%= link_to "Excluir", blogger_article_comment_path(@blog, @article, comment), method: :delete, data: { confirm: "Confirma?" } %>
        <% end %>
      </div>

      <div class="divider"></div>
    <% end %>
  <% else %>
    <div class="card-content">
      Seja o primeiro a comentar
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="comments card">
  <div class="card-title"><h5>Faça um comentário</h5></div>

  <div class="card-content">
    <%= form_for([@blog, @article, @comment]) do |f| %>
      <div class="row">
        <%= f.label :commenter %>
          <%= f.text_field :commenter, required: true %>
      </div>

      <div class="row no-margin-bot">
          <%= f.label :body %>
          <%= f.text_area :body, required: true, class: "materialize-textarea" %>
      </div>

      <div class="row no-margin-top no-pad-top no-pad-bot no-margin-bot">
          <%= f.submit "Comentar", class: "btn-flat btn-large" %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row articles container">
  <div class="col center s12 m10 offset-m1">

    <h5>Crie seu blog agora mesmo</h5>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col s12 m10 offset-m1">
        <h5 class="lime-text text-accent-3">Blog FREE</h5>
        <p class="grey-text text-lighten-4">
          We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.
        </p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center">
      Copyright © 2017
    </div>
  </div>
</footer>

app/views/layouts/_most_viewed.html.erb
<div class="col s12 l4">
  <div class="card">
    <ul class="collection with-header">
      <li class="collection-header grey darken-3"><h5 class="white-text">Mais visualizados</h5></li>
      <% @blog.articles.last(5).each do |article| %>
        <%= link_to article.name, blogger_article_path(@blog, article), class: "collection-item" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav role="navigation">
  <div class="nav-wrapper">
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to "Administração", admin_setup_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Registrar", new_user_registration_path %></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <% if user_signed_in? %>
        <li><%= link_to "Administração", admin_setup_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Registrar", new_user_registration_path %></li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/_tags.html.erb
<div class="col s12 l4">
  <div class="card">
    <ul class="collection with-header">
      <li class="collection-header grey darken-3"><h5 class="white-text">Tags</h5></li>
      <li class="collection-item" style="padding-left: 10px; padding-bottom: 20px;">
        <% tags.each do |tag| %>
          <%= content_tag :span, tag, class: "tag" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog - Administração</title>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="grey lighten-4">
    <%= render "layouts/admin/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav role="navigation" class="grey darken-4">
  <div class="nav-wrapper">
    <%= link_to "BLOG - Administração", root_url, class: "brand-logo lime-text text-accent-3" %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Artigos", admin_articles_path %></li>
      <li><%= link_to "Configurações", admin_setup_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Visitar", blogger_path(@blog) %></li>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to "Artigos", admin_articles_path %></li>
      <li><%= link_to "Configurações", admin_setup_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Visitar", blogger_path(@blog) %></li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog</title>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/navbar' %>

    <header class="row" style="margin-top: 0;">
      <div class="col s12 center">
        <h1><%= link_to @blog.title, @blog.slug, class: "brand-logo grey-text text-darken-3" %></h1>
        <p><%= @blog.description %></p>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog - Área administrativa</title>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'devise', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body style="background-color: #f5f5f5;">
    <div class="devise-form">
      <%= yield %>
    </div>
  </body>
</html>